### ISSUE TITLE
List of cats 

### ISSUE THREAD

**Issue by d-hung-nguyen** [d-hung-nguyen/capstone-project-hng#1]
## Value Proposition
As a user
I want to view and manage profiles for cats and their owners,
In order to easily share and access information about cats and connect with other cat enthusiasts.
## Description
- []List of all existing cats in the database, using cards to display each cat 
## Acceptance Criteria
- [] When the list is empty, display a message: "No cats found. Please add a new cat profile."
 -[] Each cat profile card should display the cat's name, age, and breed, color, dob, id number
- [] Status: active or inactive.
##Tasks
- [] create modal (schema) for cat
- [] Call the data for cats through end point api for cats/index.js with. GET method. Handle error 
- [] set up dbConnect through .env.local
- [] create CatsList component. Date fetch from pages/api/cats
- [] Create a cats.js page for listing cat profiles
