### ISSUE TITLE
Dynamic Navigation Update

### ISSUE THREAD

**Issue by d-hung-nguyen** [d-hung-nguyen/capstone-project-hng#17]
### Value Proposition
As a user,
I want the navigation menu to update dynamically,
In order to access active cat profiles directly from the navigation.

### Description
The main navigation is updated to include a new item for each activated cat profile dynamically.
### Acceptance Criteria

- [ ]  A new navigation item appears for each activated cat profile.
- [ ]  Each new navigation item links to the dedicated page of the activated cat profile.
- [ ]  The navigation update is dynamic and reflects in real-time as cat profiles are activated or deactivated.

### Tasks

- [ ]  Implement dynamic update functionality in the navigation component.
- [ ]  Ensure that navigation items are added or removed based on the activation status of cat profiles.
